# Generated by Django 4.1.5 on 2023-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_country_contact_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="contacts/contact/avatar/"),
        ),
    ]
