# Generated by Django 4.1.5 on 2023-03-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contact_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts.country",
            ),
        ),
    ]
