# Generated by Django 4.1.5 on 2023-03-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_groups_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, max_length=300, null=True, upload_to="contacts/contact/avatar/"
            ),
        ),
    ]
